# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: joke_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12joke_service.proto\x12\x04joke\"h\n\x0bJokeRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x14\n\x07\x63ontext\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bmax_results\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\n\n\x08_contextB\x0e\n\x0c_max_results\"\xbe\x01\n\x0cJokeResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x17\n\x0frelevance_score\x18\x05 \x01(\x02\x12\x1f\n\x17is_clarification_needed\x18\x06 \x01(\x08\x12!\n\x14\x63larification_prompt\x18\x07 \x01(\tH\x00\x88\x01\x01\x42\x17\n\x15_clarification_prompt\"2\n\rJokesResponse\x12!\n\x05jokes\x18\x01 \x03(\x0b\x32\x12.joke.JokeResponse\"_\n\x0f\x46\x65\x65\x64\x62\x61\x63kRequest\x12\x0f\n\x07joke_id\x18\x01 \x01(\t\x12\r\n\x05liked\x18\x02 \x01(\x08\x12\x1a\n\rfeedback_text\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_feedback_text\"E\n\x10\x46\x65\x65\x64\x62\x61\x63kResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"^\n\x0e\x41\x64\x64JokeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12\x13\n\x06source\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_source2\xf1\x01\n\x0bJokeService\x12\x32\n\x07GetJoke\x12\x11.joke.JokeRequest\x1a\x12.joke.JokeResponse\"\x00\x12\x34\n\x08GetJokes\x12\x11.joke.JokeRequest\x1a\x13.joke.JokesResponse\"\x00\x12\x41\n\x0eRecordFeedback\x12\x15.joke.FeedbackRequest\x1a\x16.joke.FeedbackResponse\"\x00\x12\x35\n\x07\x41\x64\x64Joke\x12\x14.joke.AddJokeRequest\x1a\x12.joke.JokeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'joke_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JOKEREQUEST']._serialized_start=28
  _globals['_JOKEREQUEST']._serialized_end=132
  _globals['_JOKERESPONSE']._serialized_start=135
  _globals['_JOKERESPONSE']._serialized_end=325
  _globals['_JOKESRESPONSE']._serialized_start=327
  _globals['_JOKESRESPONSE']._serialized_end=377
  _globals['_FEEDBACKREQUEST']._serialized_start=379
  _globals['_FEEDBACKREQUEST']._serialized_end=474
  _globals['_FEEDBACKRESPONSE']._serialized_start=476
  _globals['_FEEDBACKRESPONSE']._serialized_end=545
  _globals['_ADDJOKEREQUEST']._serialized_start=547
  _globals['_ADDJOKEREQUEST']._serialized_end=641
  _globals['_JOKESERVICE']._serialized_start=644
  _globals['_JOKESERVICE']._serialized_end=885
# @@protoc_insertion_point(module_scope)
